### ISSUE TITLE
Preset memory selection

### ISSUE THREAD

**Issue by ruudboon** [bitfocus/companion-module-panasonic-camera-controller#2]
Would it be possible to add preset selection support?

**Comment by fdebeer** [comment]
presets are stored in the camera. not in the controller.

**Comment by McHauge** [comment]
@ruudboon it would be possible, but as mentioned it's stored on the camera but the RP60, RP120 and RP150 can recall them on the selected camera. 
![image](https://user-images.githubusercontent.com/31018035/107359043-7b596800-6ad4-11eb-87ac-0ebe5a5b8197.png)

**Comment by fdebeer** [comment]
question is, why would you want to control the presets on the controller, when you can directly adres them in the camera?

**Comment by McHauge** [comment]
@fdebeer one ide could be so more than one can load presets on the selected camera directly, or if you just want that functionality on a streamdeck besides you rather than in the middle. I see it as the same as why would you want to be able to select the camera in this module

**Comment by McHauge** [comment]
Preset memory and tracing memory has been added to v1.0.1 of the module.

**Comment by McHauge** [comment]
@ruudboon All available controls with presets over ethernet, is now implemented, so anything else, needs to be done directly to the camera, sorry. but that is on Panasonic, by making it so limited.
