### ISSUE TITLE
BGH1 Support request

### ISSUE THREAD

**Issue by PhotoJoseph** [bitfocus/companion-module-panasonic-camera-controller#4]
I have no idea how open or available the resources needed would be, but the new [BGH1](https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/products/bgh1/index.html) (box camera) can be controlled completely over ethernet using the LUMIX Tether app… so theoretically, it could be controlled in Companion!

**Comment by McHauge** [comment]
that would be a part of the PTZ module if possible, not the PTZ controller module. there are no cameras being controlled in this module. all so do you have a link to the API for the camera

**Comment by JeffreyDavidsz** [comment]
Create a new request please in the correct repo
