### ISSUE TITLE
Camera Tally LEDs

### ISSUE THREAD

**Issue by daniep01** [bitfocus/companion-module-panasonic-camera-controller#5]
It would be great if companion could control the camera tally indicators on the RP50 controller. Currently I can do this by GPI on the 15way connector but it must also be possible over IP.

**Comment by McHauge** [comment]
I'm confused about what tally lights? also, all actions that are available for the controllers have already been added, it's a super limited interface on these controllers, and they specifically say in the docs, to connect to the camera instead, for other options.

Would have thought with the scale of the interface on the camera's that the interface on the controllers would have been a lot bigger than it is.

**Comment by daniep01** [comment]
The LEDs above the camera selection buttons can be turned red to indicate which camera is live. This can be done from the GPI connector on the back (I've done this) or from the Panasonic SDI switcher over a network connection (according to the manual). Unfortunately I don't have access to the switcher to sniff the packets and as you say it doesn't appear to be in the  documented protocol.

**Comment by McHauge** [comment]
@daniep01 I'll be very confused if the lights don't follow the camera ID selected in the unit. I don't see why you would need to be able to control it from here. I'm pretty sure that if you want to control the tally lights on the cameras that you will have to either use the GPIO or connect all cameras to a companion, and just use the tally variables. Like I Said it's not a part of the protocol, so... And from what I know there is no web interface on the controllers. so you're limited to the hardware entrance via the GPIO.

**Comment by JeffreyDavidsz** [comment]
The selection lights are different then tally indicators in the controller. But as far as I'm aware you can use these options:
The gpi port (which you did)
Setting the variable to follow in the PTZ camera itself. It will indicate on the controller also. If done this many times.
Both ways the controller will indicate tally (at least on the 150

**Comment by JeffreyDavidsz** [comment]
So try the camera module first

**Comment by McHauge** [comment]
Because of the fact that this is (as I see it) blocked by Panasonic, by it not being apart of the API, I'll close this for now.
