### ISSUE TITLE
Panasonic AW-RP150

### ISSUE THREAD

**Issue by nikxxbari** [bitfocus/companion-module-panasonic-camera-controller#6]
I want to report a problem regarding the Panasonic AW-rp150 controller.  When I create a new instance with this device in Companion 2.1.3, the web interface stops working.  I have had the same problem with other computers as well.  Thank you for your support.

**Comment by McHauge** [comment]
@nikxxbari Hi would it be possible for you to test thist out with the 2.2.0 beta versions, just to see if that has an effect, as that is the main version i did tests on with the rp150

**Comment by nikxxbari** [comment]
@McHauge thank you for your support! I confirm that with v.2.2.0 everything works well!
