### ISSUE TITLE
add a instance under 2.1.3 don't work

### ISSUE THREAD

**Issue by 6RomN6** [bitfocus/companion-module-panasonic-camera-controller#7]
As soon i add a Instance in 2.1.3 6b6820cd-2696 companion lost connection. I have no Controller in the Network, but i think this shouldn't happen. I get Companion only back to work i delete everything.

in companion 2.1.3 you don't see the instance, if you upgrade to the beta 2.2.0 you see the instance and everything is working... i think there is something wrong.

Best regards 

Roman

**Comment by McHauge** [comment]
@6RomN6 Please take a look at the companion 2.2.0 beta's as this is where the module was developed further, and when it got ported back to 2.1.3 something broke. I think you are the third or so who have run into this issue. so we are aware of it, but it's not necessarily enough to prompt a totally new release. as for new modules can't be updated individually but if they could it would certainly have been reverted back to the module version in companion 2.1.2

**Comment by IronChefBoyardee** [comment]
I also ran into this issue on Windows 10. After adding the preset (Does not have to be connected to the network, this also happens when running Localhost), Companion loses connection, becomes unresponsive, and is completely unresponsive until deleting ...\AppData\Roaming\Companion. Had the same issue come up on four different computers, all Windows 10.

**Comment by McHauge** [comment]
@IronChefBoyardee did you try the betas, as suggested below, we cant update the module inside 2.1.3 after a release, so the only fix is the beta's.

**Comment by Julusian** [comment]
Fixed in the latest 2.2 beta build.

@McHauge Before the config has been saved the fields are undefined, so it was doing a `setInterval(getStatus, undefined` which caused it to execute as fast as possible. also it was polling `http://undefined:undefined`
